# Generated by Django 4.2.3 on 2023-07-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0002_poem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='input_emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='input_sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
