# Generated by Django 4.2.3 on 2023-07-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0004_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='poem',
        ),
        migrations.AddField(
            model_name='poem',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='catalyst.prompt'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='poem_prompt',
            field=models.CharField(default='', max_length=300),
        ),
    ]
