# Generated by Django 4.2.3 on 2023-07-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0005_remove_prompt_poem_poem_prompt_prompt_poem_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='poem_prompt',
        ),
        migrations.AddField(
            model_name='prompt',
            name='poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='catalyst.poem'),
        ),
    ]
