# Generated by Django 4.2.3 on 2023-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0006_remove_poem_prompt_remove_prompt_poem_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='poem',
        ),
        migrations.AddField(
            model_name='prompt',
            name='inputs',
            field=models.ManyToManyField(to='catalyst.poem'),
        ),
    ]
