# Generated by Django 4.2.3 on 2023-07-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0010_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='response',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='catalyst.poem'),
        ),
    ]
