# Generated by Django 4.2.3 on 2023-07-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0011_poem_response_alter_prompt_poem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
