# Generated by Django 4.2.3 on 2023-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0013_rename_response_poem_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='category',
            field=models.CharField(choices=[('relationships and love', 'relationships and love'), ('nature and environment', 'natural and environment'), ('personal growth and relationship', 'personal growth and relationship'), ('social issues and advocacy', 'social issues and advocacy'), ('mythology and folklore', 'mythology and folklore'), ('surrealism and dreams', 'surrealism and dreams'), ('history', 'history'), ('identity and diversity', 'identity and diversity'), ('imagery and symbolism', 'imagery and symbolism')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='poem',
            name='theme',
            field=models.CharField(choices=[('association', 'association'), ('emotion', 'emotion'), ('exploration', 'exploration'), ('historical and cultural', 'historical and cultural'), ('conceptual', 'conceptual')], default='', max_length=50),
        ),
    ]
