# Generated by Django 4.2.3 on 2023-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0014_alter_poem_category_alter_poem_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('painting', 'painting'), ('drawing', 'drawing'), ('sculpture', 'sculpture'), ('printmaking', 'printmaking'), ('digital art', 'digital art'), ('illustration', 'illustration'), ('photography', 'photography'), ('mixed media', 'mixed media')], default='', max_length=50)),
                ('theme', models.CharField(choices=[('PORTRAITURE', 'portraiture'), ('TEXTURE', 'texture'), ('SYMBOLISM', 'symbolism'), ('NATURE_AND_LANDSCAPES', 'nature and landscapes'), ('STORYTELLING_AND_NARRATIVE', 'storytelling and narrative'), ('ABSTRACTION', 'abstraction'), ('SOCIAL_COMMENTARY', 'social commentary'), ('LIGHT_AND_SHADOW', 'light and shadow'), ('COLLAGE_AND_MIXED_MEDIA', 'collage and mixed media'), ('EXPERIMENTATION', 'experimentation'), ('CONCEPTUAL', 'conceptual'), ('MINIMALISM', 'minimalism'), ('MOVEMENT_AND_ENERGY', 'movement and energy'), ('HARMONY_AND_BALANCE', 'harmony and balance')], default='', max_length=50)),
                ('sentiment', models.CharField(choices=[('HARMONY', 'harmony'), ('SERENITY', 'serenity'), ('SOLITUDE', 'solitude'), ('RESILIENCE', 'resilience'), ('WONDER', 'wonder'), ('RENEWAL', 'renewal'), ('FRAGILITY', 'fragility'), ('MAJESTY', 'majesty'), ('TRANSIENCE', 'transience'), ('CONNECTION', 'connection')], default='', max_length=50)),
                ('emotion', models.CharField(choices=[('JOY', 'joy'), ('COURAGE', 'courage'), ('MELANCHOLY', 'melancholy'), ('EUPHORIA', 'euphoria'), ('LONGING', 'longing'), ('HOPE', 'hope'), ('AWE', 'awe'), ('BLISS', 'bliss'), ('ANGUISH', 'anguish'), ('GRIEF', 'grief')], default='', max_length=50)),
                ('temperature', models.IntegerField(default=1)),
                ('output', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='poem',
            name='category',
            field=models.CharField(choices=[('relationships and love', 'relationships and love'), ('nature and environment', 'natural and environment'), ('personal growth and reflection', 'personal growth and REFLECTION'), ('social issues and advocacy', 'social issues and advocacy'), ('mythology and folklore', 'mythology and folklore'), ('surrealism and dreams', 'surrealism and dreams'), ('history', 'history'), ('identity and diversity', 'identity and diversity'), ('imagery and symbolism', 'imagery and symbolism')], default='', max_length=50),
        ),
    ]
