# Generated by Django 4.2.3 on 2023-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0015_visualart_alter_poem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualart',
            name='emotion',
            field=models.CharField(choices=[('joy', 'joy'), ('courage', 'courage'), ('melancholy', 'melancholy'), ('euphoria', 'euphoria'), ('longing', 'longing'), ('hope', 'hope'), ('awe', 'awe'), ('bliss', 'bliss'), ('anguish', 'anguish'), ('grief', 'grief')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='visualart',
            name='sentiment',
            field=models.CharField(choices=[('harmony', 'harmony'), ('serenity', 'serenity'), ('solitude', 'solitude'), ('resilience', 'resilience'), ('wonder', 'wonder'), ('renewal', 'renewal'), ('fragility', 'fragility'), ('majesty', 'majesty'), ('transience', 'transience'), ('connection', 'connection')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='visualart',
            name='theme',
            field=models.CharField(choices=[('portraiture', 'portraiture'), ('texture', 'texture'), ('symbolism', 'symbolism'), ('nature and landscapes', 'nature and landscapes'), ('storytelling and narrative', 'storytelling and narrative'), ('abstraction', 'abstraction'), ('social commentary', 'social commentary'), ('light and shadow', 'light and shadow'), ('collage and mixed media', 'collage and mixed media'), ('experimentation', 'experimentation'), ('conceptual', 'conceptual'), ('minimalism', 'minimalism'), ('movement and energy', 'movement and energy'), ('harmony and balance', 'harmony and balance')], default='', max_length=50),
        ),
    ]
