# Generated by Django 4.2.3 on 2023-07-17 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0033_alter_visualart_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualarts', to=settings.AUTH_USER_MODEL),
        ),
    ]
