# Generated by Django 4.2.3 on 2023-07-17 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0034_visualart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('association', 'association'), ('emotion', 'emotion'), ('exploration', 'exploration'), ('historical and cultural', 'historical and cultural'), ('conceptual', 'conceptual')], default='', max_length=50)),
                ('category', models.CharField(choices=[('relationships and love', 'relationships and love'), ('nature and environment', 'natural and environment'), ('personal growth and reflection', 'personal growth and REFLECTION'), ('social issues and advocacy', 'social issues and advocacy'), ('mythology and folklore', 'mythology and folklore'), ('surrealism and dreams', 'surrealism and dreams'), ('history', 'history'), ('identity and diversity', 'identity and diversity'), ('imagery and symbolism', 'imagery and symbolism')], default='', max_length=50)),
                ('sentiment', models.CharField(choices=[('harmony', 'harmony'), ('resilience', 'resilience'), ('fragility', 'fragility'), ('majesty', 'majesty'), ('serenity', 'serenity'), ('wonder', 'wonder'), ('transience', 'transience'), ('connection', 'connection'), ('solitude', 'solitude'), ('renewal', 'renewal')], default='', max_length=50)),
                ('emotion', models.CharField(choices=[('joy', 'joy'), ('courage', 'courage'), ('melancholy', 'melancholy'), ('euphoria', 'euphoria'), ('longing', 'longing'), ('hope', 'hope'), ('awe', 'awe'), ('bliss', 'bliss'), ('anguish', 'anguish'), ('grief', 'grief')], default='', max_length=50)),
                ('output', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='poem',
        ),
        migrations.DeleteModel(
            name='Poem',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
