# Generated by Django 4.2.3 on 2023-07-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0036_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='style',
            field=models.CharField(choices=[('stream of conciousness', 'stream of consciousness'), ('time', 'time'), ('character development', 'character development'), ('poetry', 'poetry'), ('word play', 'word play'), ('story starter', 'story starter'), ('image', 'image'), ('storytelling through objects', 'storytelling through objects'), ('flash', 'flash'), ('point of view shift', 'point of view shift'), ('memoir', 'memoir'), ('dialogue', 'dialogue')], default='', max_length=50),
        ),
    ]
