# Generated by Django 4.2.3 on 2023-07-17 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0037_write_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploration', models.CharField(choices=[('MOOD_BASED_COMPOSITION', 'mood-based composition'), ('GENRE_FUSION', 'genre fusion'), ('MUSICAL_STORYTELLING', 'musical storytelling'), ('NATURE_SOUNDSCAPE', 'nature soundscape'), ('RHYTHMIC_EXPLORATION', 'rhythmic exploration'), ('COLLABORATIVE_COMPOSITION', 'collaborative composition'), ('MINIMALISM', 'minimalism'), ('MASHUP_OR_REMIX', 'mashup or remix'), ('MUSIC_FOR_VISUALS', 'music for visuals'), ('CINEMATIC_SCORE', 'cinematic score'), ('MUSICAL_HAIKU', 'musical haiku'), ('ONE_NOTE_CHALLENGE', 'one-note challenge'), ('INCORPORATE_UNCONVENTIONAL_INSTRUMENTS', 'incorporate unconventional instruments'), ('MUSIC_INSPIRED_BY_ART', 'music inspired by art'), ('MUSICAL_TIME_TRAVEL', 'musical time travel')], default='', max_length=50)),
                ('concept', models.CharField(choices=[('DYNAMICS', 'dynamics'), ('TEMPO', 'tempo'), ('TIMBRE', 'timbre'), ('MELODY', 'melody'), ('RHYTHM', 'rhythm'), ('TEXTURE', 'texture'), ('FORM', 'form'), ('EXPRESSION', 'expression'), ('PITCH', 'pitch')], default='', max_length=50)),
                ('element', models.CharField(choices=[('FIRE', 'fire'), ('WATER', 'water'), ('EARTH', 'earth'), ('AIR', 'air'), ('LIGHT', 'light'), ('DARKNESS', 'darkness'), ('SOUND', 'sound'), ('MOVEMENT', 'movement'), ('TIME', 'time'), ('SPACE', 'space')], default='', max_length=50)),
                ('emotion', models.CharField(choices=[('joy', 'joy'), ('courage', 'courage'), ('melancholy', 'melancholy'), ('euphoria', 'euphoria'), ('longing', 'longing'), ('hope', 'hope'), ('awe', 'awe'), ('bliss', 'bliss'), ('anguish', 'anguish'), ('grief', 'grief')], default='', max_length=50)),
                ('temperature', models.IntegerField(default=1)),
                ('output', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
