# Generated by Django 4.2.3 on 2023-07-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0038_alter_movement_user_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='concept',
            field=models.CharField(choices=[('dynamics', 'dynamics'), ('tempo', 'tempo'), ('timbre', 'timbre'), ('melody', 'melody'), ('rhythm', 'rhythm'), ('texture', 'texture'), ('form', 'form'), ('expression', 'expression'), ('pitch', 'pitch')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='music',
            name='element',
            field=models.CharField(choices=[('fire', 'fire'), ('water', 'water'), ('earth', 'earth'), ('air', 'air'), ('light', 'light'), ('darkness', 'darkness'), ('sound', 'sound'), ('movement', 'movement'), ('time', 'time'), ('space', 'space')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='music',
            name='exploration',
            field=models.CharField(choices=[('mood-based composition', 'mood-based composition'), ('genre fusion', 'genre fusion'), ('musical storytelling', 'musical storytelling'), ('nature soundscape', 'nature soundscape'), ('rhythmic exploration', 'rhythmic exploration'), ('collaborative composition', 'collaborative composition'), ('minimalism', 'minimalism'), ('mashup or remix', 'mashup or remix'), ('music for visuals', 'music for visuals'), ('cinematic score', 'cinematic score'), ('musical haiku', 'musical haiku'), ('one-note challenge', 'one-note challenge'), ('incorporate unconventional instruments', 'incorporate unconventional instruments'), ('music inspired by art', 'music inspired by art'), ('musical time travel', 'musical time travel')], default='', max_length=50),
        ),
    ]
