# Generated by Django 4.2.3 on 2023-07-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0039_alter_music_concept_alter_music_element_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='length',
            field=models.CharField(choices=[('one word', 'one word'), ('prompt', 'prompt')], default=''),
        ),
    ]
