# Generated by Django 4.2.3 on 2023-07-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0040_music_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='length',
            field=models.CharField(choices=[('one word', 'one word'), ('prompt', 'prompt')], default=''),
        ),
        migrations.AddField(
            model_name='visualart',
            name='length',
            field=models.CharField(choices=[('one word', 'one word'), ('prompt', 'prompt')], default=''),
        ),
        migrations.AddField(
            model_name='write',
            name='length',
            field=models.CharField(choices=[('one word', 'one word'), ('prompt', 'prompt')], default=''),
        ),
    ]
