# Generated by Django 4.2.3 on 2023-07-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0042_alter_movement_length_alter_music_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='write',
            old_name='length',
            new_name='prompt_length',
        ),
        migrations.AddField(
            model_name='write',
            name='input_length',
            field=models.CharField(default='', max_length=300),
        ),
    ]
