# Generated by Django 4.2.3 on 2023-07-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0043_rename_length_write_prompt_length_write_input_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='prompt_length',
            field=models.CharField(choices=[('one word', 'one word'), ('three words', 'three words'), ('prompt', 'prompt')]),
        ),
    ]
