# Generated by Django 4.2.3 on 2023-07-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0045_alter_write_input_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualart',
            name='input_length',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
