# Generated by Django 4.2.3 on 2023-07-18 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0046_visualart_input_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualart',
            old_name='length',
            new_name='prompt_length',
        ),
    ]
