# Generated by Django 4.2.3 on 2023-07-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0047_rename_length_visualart_prompt_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualart',
            name='prompt_length',
            field=models.CharField(choices=[('one word', 'one word'), ('three words', 'three words'), ('prompt', 'prompt')]),
        ),
    ]
