# Generated by Django 4.2.3 on 2023-07-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0049_remove_movement_length_remove_music_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualart',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=0.8, max_digits=3),
        ),
    ]
