# Generated by Django 4.2.3 on 2023-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0050_alter_visualart_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='temperature',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='music',
            name='concept',
            field=models.CharField(choices=[('dynamics', 'dynamics'), ('tempo', 'tempo'), ('timbre', 'timbre'), ('melody', 'melody'), ('rhythm', 'rhythm'), ('texture', 'texture'), ('form', 'form'), ('expression', 'expression'), ('pitch', 'pitch'), ('notation', 'notation')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='visualart',
            name='temperature',
            field=models.FloatField(default=0.8),
        ),
    ]
