# Generated by Django 4.2.3 on 2023-07-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0051_write_temperature_alter_music_concept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_movements', to='catalyst.movement'),
        ),
        migrations.AddField(
            model_name='music',
            name='visual_art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_arts', to='catalyst.visualart'),
        ),
        migrations.AddField(
            model_name='music',
            name='write',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_writes', to='catalyst.write'),
        ),
    ]
