# Generated by Django 4.2.3 on 2023-07-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0053_alter_movement_user_alter_music_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='music',
            name='visual_art',
        ),
        migrations.RemoveField(
            model_name='music',
            name='write',
        ),
    ]
