# Generated by Django 4.2.3 on 2023-07-18 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0056_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='create',
            name='music',
        ),
        migrations.RemoveField(
            model_name='create',
            name='visual_art',
        ),
        migrations.RemoveField(
            model_name='create',
            name='write',
        ),
        migrations.AddField(
            model_name='movement',
            name='create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_creates', to='catalyst.create'),
        ),
        migrations.AddField(
            model_name='music',
            name='create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_creates', to='catalyst.create'),
        ),
        migrations.AddField(
            model_name='visualart',
            name='create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visual_arts_creates', to='catalyst.create'),
        ),
        migrations.AddField(
            model_name='write',
            name='create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writes_creates', to='catalyst.create'),
        ),
        migrations.AlterField(
            model_name='create',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creates_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
