# Generated by Django 4.2.3 on 2023-07-18 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0057_remove_create_movement_remove_create_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creates_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='create',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creates_music', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='create',
            name='visual_art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creates_visual_arts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='create',
            name='write',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creates_writes', to=settings.AUTH_USER_MODEL),
        ),
    ]
