# Generated by Django 4.2.3 on 2023-07-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0058_create_movement_create_music_create_visual_art_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write',
            name='create',
        ),
        migrations.AddField(
            model_name='write',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
