# Generated by Django 4.2.3 on 2023-07-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0059_remove_write_create_write_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='date_created',
            field=models.DateTimeField(
                auto_now_add=True, default='2022-08-07'),
            preserve_default=False,
        ),
    ]
