# Generated by Django 4.2.3 on 2023-07-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0060_write_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='write',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
