# Generated by Django 4.2.3 on 2023-07-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0061_rename_date_created_write_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movement',
            name='create',
        ),
        migrations.RemoveField(
            model_name='music',
            name='create',
        ),
        migrations.RemoveField(
            model_name='visualart',
            name='create',
        ),
        migrations.RemoveField(
            model_name='write',
            name='note',
        ),
        migrations.DeleteModel(
            name='Create',
        ),
    ]
