# Generated by Django 4.2.3 on 2023-07-19 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0062_note_remove_movement_create_remove_music_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writes_notes', to='catalyst.note'),
        ),
    ]
