# Generated by Django 4.2.3 on 2023-07-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0063_write_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='write',
            name='emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='write',
            name='prompt_length',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='write',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='write',
            name='style',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='write',
            name='theme',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
