# Generated by Django 4.2.3 on 2023-07-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0064_alter_write_category_alter_write_emotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='temperature',
            field=models.FloatField(default=0.8),
        ),
    ]
