# Generated by Django 4.2.3 on 2023-07-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0065_alter_write_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-08-07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualart',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visual_art_notes', to='catalyst.note'),
        ),
        migrations.AlterField(
            model_name='visualart',
            name='emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visualart',
            name='medium',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visualart',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visualart',
            name='theme',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
