# Generated by Django 4.2.3 on 2023-07-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0066_visualart_created_at_visualart_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-08-07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_notes', to='catalyst.note'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movement',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movement',
            name='somatic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movement',
            name='theme',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
