# Generated by Django 4.2.3 on 2023-07-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0071_write_input_temperature_alter_write_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='input_temperature',
            field=models.FloatField(blank=True),
        ),
    ]
