# Generated by Django 4.2.3 on 2023-07-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0072_alter_write_input_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='temperature',
            field=models.CharField(max_length=50),
        ),
    ]
