# Generated by Django 4.2.3 on 2023-07-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0073_alter_write_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='music',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='visualart',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='write',
            name='input_temperature',
        ),
        migrations.RemoveField(
            model_name='write',
            name='temperature',
        ),
    ]
