# Generated by Django 4.2.3 on 2023-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0074_remove_movement_temperature_remove_music_temperature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_text', models.TextField(blank=True)),
            ],
        ),
    ]
