# Generated by Django 4.2.3 on 2023-07-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0075_welcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='note',
        ),
        migrations.RemoveField(
            model_name='music',
            name='note',
        ),
        migrations.RemoveField(
            model_name='visualart',
            name='note',
        ),
        migrations.RemoveField(
            model_name='write',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_movements', to='catalyst.movement'),
        ),
        migrations.AddField(
            model_name='note',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_music', to='catalyst.music'),
        ),
        migrations.AddField(
            model_name='note',
            name='visual_art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_visual_arts', to='catalyst.visualart'),
        ),
        migrations.AddField(
            model_name='note',
            name='write',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_written', to='catalyst.write'),
        ),
    ]
