# Generated by Django 4.2.3 on 2023-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0076_remove_movement_note_remove_music_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300)),
                ('definition', models.TextField(blank=True)),
            ],
        ),
    ]
