# Generated by Django 4.2.3 on 2023-07-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0085_movement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visualart',
            name='save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='write',
            name='save',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movement',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='music',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='visualart',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='write',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
