# Generated by Django 4.2.3 on 2023-07-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0088_alter_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='user_input',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
