# Generated by Django 4.2.3 on 2023-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0091_remove_write_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='previous_prompt',
            field=models.TextField(blank=True),
        ),
    ]
