# Generated by Django 4.2.3 on 2023-07-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0092_write_previous_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='new_instance',
            field=models.TextField(blank=True),
        ),
    ]
