# Generated by Django 4.2.3 on 2023-07-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0093_write_new_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='antonym',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='joke',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='synonym',
            field=models.CharField(blank=True),
        ),
    ]
