# Generated by Django 4.2.3 on 2023-07-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0094_definition_antonym_definition_joke_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='color',
            field=models.TextField(blank=True),
        ),
    ]
