# Generated by Django 4.2.3 on 2023-07-25 23:48

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0095_definition_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png', 'video/mp4'])]),
        ),
    ]
