# Generated by Django 4.2.3 on 2023-07-26 00:09

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0096_music_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write',
            name='new_instance',
        ),
        migrations.RemoveField(
            model_name='write',
            name='previous_prompt',
        ),
        migrations.AddField(
            model_name='movement',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png', 'video/mp4'])]),
        ),
        migrations.AddField(
            model_name='visualart',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png', 'video/mp4'])]),
        ),
        migrations.AddField(
            model_name='write',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png', 'video/mp4'])]),
        ),
    ]
