# Generated by Django 4.2.3 on 2023-07-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0098_remove_movement_file_remove_music_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualart',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
