# Generated by Django 4.2.3 on 2023-07-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0100_alter_visualart_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='music',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='write',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
