# Generated by Django 4.2.3 on 2023-07-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0101_movement_is_deleted_music_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='write',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
