# Generated by Django 4.2.3 on 2023-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0102_alter_movement_is_deleted_alter_music_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='prompt_length',
            field=models.CharField(choices=[('one word', 'one word'), ('a few words', 'a few words'), ('a sentence or two', 'a sentence or two')]),
        ),
        migrations.AlterField(
            model_name='music',
            name='prompt_length',
            field=models.CharField(choices=[('one word', 'one word'), ('a few words', 'a few words'), ('a sentence or two', 'a sentence or two')]),
        ),
        migrations.AlterField(
            model_name='visualart',
            name='prompt_length',
            field=models.CharField(choices=[('one word', 'one word'), ('a few words', 'a few words'), ('a sentence or two', 'a sentence or two')]),
        ),
    ]
