# Generated by Django 4.2.3 on 2023-07-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0104_visualart_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='hex',
            field=models.CharField(blank=True),
        ),
    ]
