# Generated by Django 4.2.3 on 2023-08-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0105_definition_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='prompt_length',
            field=models.CharField(choices=[('One word', 'One word'), ('A few words', 'A few words'), ('A sentence or two', 'A sentence or two')]),
        ),
        migrations.AlterField(
            model_name='music',
            name='prompt_length',
            field=models.CharField(choices=[('One word', 'One word'), ('A few words', 'A few words'), ('A sentence or two', 'A sentence or two')]),
        ),
        migrations.AlterField(
            model_name='visualart',
            name='prompt_length',
            field=models.CharField(choices=[('One word', 'One word'), ('A few words', 'A few words'), ('A sentence or two', 'A sentence or two')]),
        ),
    ]
